name: CI-basic

on:
    push:
        branches:
            # - main
            - feature/*

    workflow_dispatch:
    

jobs:
    produce:
        runs-on: ubuntu-latest
        outputs:
            sketch: ${{ steps.generate-sketch.outputs.sketch }}
        steps:
          - uses: actions/checkout@v4

          - name: Generate and Export sketch
            id: generate-sketch
            run: |
                set -euo pipefail

                chmod +x misc/draw
                misc/draw >> "$GITHUB_OUTPUT"
    consume:
        runs-on: ubuntu-latest
        needs: produce
        steps:
          - run: |
                echo $GITHUB_OUTPUT
                echo "from_produce: ${{ needs.produce.outputs.sketch }}"