name: CI-basic

# GHA runs each action in Node.js runtime: @v6 uses Node 24
on:
    push:
        branches:
            - feature/*
    workflow_dispatch:
    

jobs:
    misc-script:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
          - uses: actions/checkout@v6
          - name: Run draw script
            timeout-minutes: 1
            run: |
                set -euo pipefail

                chmod +x misc/draw
                misc/draw

# pass variables on steps via GITHUB_OUTPUT/_ENV
    produce:
        runs-on: ubuntu-latest
        outputs:
            foo: ${{ steps.generate-foo.outputs.foo }}
        steps:
          - uses: actions/checkout@v6

          - name: Generate and export foo
            id: generate-foo
            run: |
                foo=bar

                # 1) step output (for job output)
                echo "foo=${foo}" >> "$GITHUB_OUTPUT"
                
                # 2) job-scoped env variable
                echo "FOO=${foo}" >> "$GITHUB_ENV"

          - name: Inspect
            run: |
                echo "foo (via step-output):     ${{ steps.generate-foo.outputs.foo }}"
                echo "FOO (via GITHUB_ENV):      $FOO"

    consume:
        runs-on: ubuntu-latest
        needs: [misc-script, produce]
        strategy:
            matrix:
                environ: [dev, prod]
        steps:
          - name: Inspect values in the consume-job (FOO is unset)
            run: |
                echo "Environment:                ${{ matrix.environ }}"
                echo "Value from produce-job:     ${{ needs.produce.outputs.foo }}"
                echo "FOO in consume-job:         ${FOO:-<UNSET>}"

