name: Github-Script - Step 3

on:
    issues:
        types: [opened]

jobs:
    interact-with-issue:
        runs-on: ubuntu-latest
        steps:
          - name: Comment on issue
            uses: actions/github-script@v8
            with:
                script: |
                    await github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        body: '👋 Thanks for opening this issue!'
                    })
          - name: Add label
            uses: actions/github-script@v8
            with:
                script: |
                    await github.rest.issues.addLabels({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        labels: ['Triage']
                    })
