name: Github-Script - Step 3

on:
    issues:
        types: [opened]

jobs:
    interact-with-issue:
        runs-on: ubuntu-latest
        permissions:
            issues: write       # give the right (write) permissions
        steps:
          - name: Comment on issue with logging
            id: cmt-issue
            uses: actions/github-script@v8
            with:
                script: |
                    core.info(`Issue opened by: ${context.actor}`);
                    core.info(`Issue number by: ${context.issue.number}`);

                    // Fail-fast if something unexpected
                    if (!context.issue.number) {
                        core.setFailed("No issue number found in context");
                    }

                    const response = await github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        body: `👋 Thanks for opening this issue, @${context.actor}`
                    })

                    core.info(`Comment created at: ${response.data.html_url}`);
                    core.setOutput("cmt_id", response.data.id);
                    core.setOutput("cmt_url", response.data.html_url);

          - name: Add label
            uses: actions/github-script@v8
            with:
                script: |
                    await github.rest.issues.addLabels({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        labels: ['triage']
                    })

          - name: Log results
            run: |
                echo "Comment ID:       ${{steps.cmt-issue.outputs.cmt_id}}"
                echo "Comment URL:      ${{steps.cmt-issue.outputs.cmt_url}}"
